---
title: "Analysis of Iris data set by `r params$species` species"
output: github_document
date: "`r Sys.Date()`"  

params:
  species: "setosa"
---

```{r setup, include=FALSE}
# Default option to suppress code display, messages and warnings ---------------
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

```{r}
# Extract data set of interest -------------------------------------------------
sample_data <- withr::with_seed(
  seed = 111,
  dplyr::sample_n(iris, 50)
)
```

### Summary table for species `r `params$species`   

The summary table for `r params$species` irises is displayed below.  

```{r, results='markup'}
# Output table -----------------------------------------------------------------
sample_data |>
  dplyr::filter(Species == params$species) |>
  dplyr::summarise(across(where(is.numeric), list(mean = mean, sd = sd))) |> 
  knitr::kable()
```


### Plot for species `r params$species`   

The plot for `r params$species` sepal length versus sepal width is displayed below.   

```{r, results='markup'}
# Output histogram if variable is numeric and bar plot if otherwise ------------
library(ggplot2)

sample_data |>
  dplyr::filter(Species == params$species) |>
  ggplot() +
  geom_point(aes(x = Sepal.Length, y = Sepal.Width, colour = Species)) +
  theme_minimal()
```