---
title: "Review of Regression, Fire and Dangerous Things"
author: "Erika Duan"
date: "`r Sys.Date()`"

execute:
  echo: true
  output: false
  message: false
  warning: false

format:
  gfm:
    toc: true
---

This is a review of the following blog posts:    

+ Regression, Fire and Dangerous Things [Part 1](https://elevanth.org/blog/2021/06/15/regression-fire-and-dangerous-things-1-3/)
+ Regression, Fire and Dangerous Things [Part 2](https://elevanth.org/blog/2021/06/21/regression-fire-and-dangerous-things-2-3/)
+ Regression, Fire and Dangerous Things [Part 3](https://elevanth.org/blog/2021/06/29/regression-fire-and-dangerous-things-3-3/)  

# Part 1 - the causal salad    

There are a few reasons for performing regression modelling (from [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/)).   

+ Predicting or forecasting outcomes using existing data (without caring about causal associations).  
+ Exploring associations between variables of interest and an outcome.  
+ Adjusting outcomes from a sample to infer something about a population of interest.  
+ Estimating treatment effects by comparing outcomes between a treatment and control (defined in ROS as causal inference).  

McElreath emphasises that what scientific practitioners are often looking for is a method to **separate spurious associations from true causal relationships**. This is not necessarily what regression modelling provides you with.    

```{r}

```

